"""added address in branch model

Revision ID: 2a4f299f297e
Revises: ace0fadac61b
Create Date: 2021-07-11 12:29:00.124923

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2a4f299f297e'
down_revision = 'ace0fadac61b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('branch', sa.Column('address', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('branch', 'address')
    # ### end Alembic commands ###
